### ISSUE TITLE
determine how to get the "Resources" list on the RHS

### ISSUE THREAD

**Issue by topepo** [tidymodels/tidymodels_dot_org#14]
tidymodels.org pages have a "Resources" list under the contents on the right: 

<img width="335" alt="image" src="https://github.com/tidymodels/tidymodels_dot_org/assets/5731043/97191a0b-8fa3-4fd0-aa22-9470f2e08add">

I'd like to add these back in (but it can happen after launch,  if still needed)

**Comment by EmilHvitfeldt** [comment]
closed in https://github.com/tidymodels/tidymodels_dot_org/commit/85de05104c8ce8d348172df60e9a74303c1893c1
