### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by topepo** [tidymodels/tidymodels_dot_org#15]
On the Get Started landing page, this link is broken: [Statistical Inference via Data Science: A ModernDive into R and the Tidyverse](https://tidymodels.github.io/tidymodels_dot_org/books/moderndive/).

**Comment by EmilHvitfeldt** [comment]
closed in https://github.com/tidymodels/tidymodels_dot_org/commit/1ad542c92c66179ef8e9b7d914c40fc3ce120445
