### ISSUE TITLE
Missing spaces

### ISSUE THREAD

**Issue by topepo** [tidymodels/tidymodels_dot_org#16]
The package page is missing some spaces between sentences: 

> rsample provides infrastructure for efficient data splitting and resampling.[Go to package …](https://rsample.tidymodels.org/)

etc and also

> Learn more about the tidymodels metapackage itself athttps://tidymodels.tidymodels.org/.

**Comment by EmilHvitfeldt** [comment]
I forgot when I fixed it, but it is fixed now 😄
