### ISSUE TITLE
unavailable data

### ISSUE THREAD

**Issue by NathanOnduma** [tidymodels/tidymodels_dot_org#20]
The urchins dataset used for the first of the 5 articles of the Get Started is not available. The link is somehow broken

**Comment by EmilHvitfeldt** [comment]
Thank you for the report!

I'll fix it in the morning

**Comment by NathanOnduma** [comment]
Thank you. Was wondering if the exact CSV file sits somewhere for use in the fly, otherwise, I will wait. Thanks Emil

**Comment by krz** [comment]
@NathanOnduma you can directly import the data from this link: https://github.com/tidymodels/tidymodels_dot_org/blob/main/start/models/urchins.csv

**Comment by NathanOnduma** [comment]
Thank you

**Comment by EmilHvitfeldt** [comment]
It should have been fixed in https://github.com/tidymodels/tidymodels_dot_org/commit/5ce6fb31adb51de378345d4e88091f8997954bd9. Thanks for reporting 🙌

**Comment by krz** [comment]
Thanks Emil, I can’t test it right now but earlier today the hotels data set from chapter 5 had the same issue

**Comment by EmilHvitfeldt** [comment]
It is fixed as well

**Comment by NathanOnduma** [comment]
Thanks alot  @EmilHvitfeldt . The more I learn the tidymodels, the more I am eager to learn
